name: CI/CD Pipeline with Slack Notification

on:
  push:
    branches:
      - slack-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy
      run: npm run deploy

    - name: Send Slack Notification
      if: always()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"Build ${{ job.status }} for branch ${{ github.ref }} in repository ${{ github.repository }}. Commit: ${{ github.sha }}.\"}" \
        ${{ secrets.SLACK_WEBHOOK_URL }}

name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Dependencies
        run: npm install

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        env:
          IMAGE_NAME: test-image
          VERSION: 1
          USERNAME: bigstan00
        run: |
          docker build -t $USERNAME/$IMAGE_NAME:$VERSION .

      - name: Push Docker image to Docker Hub
        env:
          IMAGE_NAME: test-image
          VERSION: 1
          USERNAME: bigstan00
        run: |
          docker push $USERNAME/$IMAGE_NAME:$VERSION

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send Slack message for build success
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'D07DPTV3N86'  # Replace with your channel ID
          slack-message: "GitHub build succeeded! 🎉\n[Build URL](${{ github.event.head_commit.url }})"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send Slack message for build failure
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'D07DPTV3N86'  # Replace with your channel ID
          slack-message: "GitHub build failed. 😞\n[Build URL](${{ github.event.head_commit.url }})"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    
