name: "Continuous Deploy"
on: 
    workflow_run: ##This is the event type that triggers the workflow
        workflows: ["Deployment Workflow"] ## This is the name of the workflow
        types: ## Indicates that the workflow that builds & should be triggered when it is pushed to Docker Hub
            - completed ## Specifies workflow is completed
jobs:
    pull_and_run_code:
        runs-on: self-hosted
        steps:
            - name: "stop the container"
              run: "docker stop test-calc || true"
            - name: "Remove the container test-calc"
              run: docker rm test-calc || true
            - name: "get the code from Docker Hub"
              run: docker pull monyslim/test-image:1
            - name: "run the image as a container"
              run: "docker run -d -p 3004:3000 --name test-calc monyslim/test-image:1"