name: CI

# Define when to trigger the Workflow
on:
    push:
        branches:
            - master
jobs:
    print-greeting:
       runs-on: ubuntu-latest
    # Define steps to execute
       steps:
          - name: Check out code
            uses: actions/checkout@v2
          - name: Print greeting
            run: |
                echo "Welcome"
          - name: "Logs into Docker Hub account"
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Build our code image   # step description: builds our Docker image
            env: 			           # sets environment variables for this step
                image_name: test-image     # image name variable
                version: 1                                  # version variable
                username: monyslim            # Docker Hub username
            run: |                                              # script to run the Docker commands
                docker build -t $username/$image_name:$version .  # builds the Docker image with the given name and version.